config/routes.rb
Rails.application.routes.draw do

  root to: 'homes#index'
  devise_for :users

  resources :pictures, only: [:index, :new, :create]
  
  resources :contents, only: [:index, :new, :create, :show, :edit, :confirm]
  patch 'contents/:id' => 'contents#update', as: 'update_content'
  delete 'contents/:id' => 'contents#destroy', as: 'destroy_content'
  post 'contents/complete'
  post 'contents/confirm'

  resources :users, only: [:show, :edit, :create]
  patch 'users/:id' => 'users#update', as: 'update_user'
  
  resources :texts, only: [:new, :create, :show, :edit]
  patch 'texts/:id' => 'texts#update', as: 'update_text'
  delete 'texts/:id' => 'texts#destroy', as: 'destroy_text'
  
  resources :points, only: [:index, :new, :show, :create]
  
  resources :carry_contents, only: [:index, :new, :create]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  has_one_attached :image
end

app/models/carry_content.rb
class CarryContent < ApplicationRecord
end

app/models/content.rb
class Content < ApplicationRecord
  has_one_attached :image
  has_many :text
  has_many :pictures
  accepts_nested_attributes_for :pictures
  belongs_to :user
end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :content
  has_many :texts
  accepts_nested_attributes_for :texts
  belongs_to :user
end

app/models/point.rb
class Point < ApplicationRecord
end

app/models/text.rb
class Text < ApplicationRecord
  belongs_to :user
  belongs_to :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :content, dependent: :destroy
  has_many :text, dependent: :destroy
  has_many :picture, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carry_contents_controller.rb
class CarryContentsController < ApplicationController
  def index
    @carry_content = current_user.picture
  end

  def new
    @carry_content= CarryContent.new
  end

  def create
    @picture = Picture.new(carry_content_params)
    @carry_content= CarryContent.new(carry_content_params)
    @carry_content.user_id = current_user.id
    @carry_content.save
    redirect_to contents_path
  end
  
  private

  def carry_content_params
    params.require(:carry_content).permit(:picture_id, :images)
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def index
    @carry_content = current_user.picture
  end

  def new
    @content= Content.new
    pictures = @content.pictures.build
    pictures.options.build
  end

  def create
    content= Content.new(content_params)
    if content.valid?
      content.save!
    else
      render :new
    end
  end
  
  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
  def confirm
  end
  
  private
  
  def carry_content_params
    params.require(:carry_content).permit(:picture_id, :images)
  end
  
  def content_params
    params.require(:content).permit(:title, :description, 
      pictures_attributes: [:text, :description,
        options_attributes: [:text]
      ]
    )
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
  end

  def new
    @carry_content = CarryContent.new
    
  end

  def create
    @picture = Picture.new(picture_params)
    if @picture.save
      redirect_to contents_path
    else
      flash.now[:alret] = "ソフト名を入力してください"
      render :new
    end
  end
  
  private
  
  def picture_params
    params.require(:picture).permit(:images)
  end
end

app/controllers/points_controller.rb
class PointsController < ApplicationController
  def index
  end

  def new
    @point = Point.new
  end

  def show
    @point = Point.find_by(id: params[:id])
  end

  def create
    @point = Point.new(point_params)
    params[:point][:question] ? @point.question = params[:point][:question].join("") : false
    if @point.save
        flash[:notice] = "診断が完了しました"
        redirect_to point_path(@point.id)
    else
        redirect_to :action => "new"
    end
  end

private
  def point_params
      params.require(:point).permit(:id, question: [])
  end
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  def new
    @carry_content = current_user.picture
    @text = Text.new
  
  end
  
  def create
    @text = Text.new(text_params)
    @text.save
    redirect_to contents_confirm_path
  end
  
  def complete 
      @text = current_user.texts.build(text_params)
      @text.save!
      carry_contents = current_user.carry_contents
      carry_contents.each do |carry_content|
      content = @text.contents.build
      content.picture_id = content.picture_id
      content.text = carry_content.text.id
      content.save
    end
    carry_contents.destroy_all
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
  
    private

  def text_params
    params.require(:text).permit(:text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  def edit
  end

  def update
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carry_contents_helper.rb
module CarryContentsHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/points_helper.rb
module PointsHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carry_contents/create.html.erb
<h1>CarryContents#create</h1>
<p>Find me in app/views/carry_contents/create.html.erb</p>

app/views/carry_contents/new.html.erb
<h1>CarryContents#new</h1>
<p>Find me in app/views/carry_contents/new.html.erb</p>

app/views/contents/confirm.html.erb
かくにんがめん
<div class="col-md-8 offset-md-1">
  <%= form_with model: @order , url: contents_complete_path do |f| %>
   <%= f.hidden_field :text, :value => @text %>
    <%= f.submit '購入確定' %>
<% end %>

app/views/contents/create.html.erb
<h1>Contents#create</h1>
<p>Find me in app/views/contents/create.html.erb</p>

app/views/contents/destroy.html.erb
<h1>Contents#destroy</h1>
<p>Find me in app/views/contents/destroy.html.erb</p>

app/views/contents/edit.html.erb
<h1>Contents#edit</h1>
<p>Find me in app/views/contents/edit.html.erb</p>

app/views/contents/index.html.erb
これでよいかし？
<div class="col-md-8 offset-md-1">

<table>
          <% if picture.image.image.attached? %>
          <small>※画像をクリックすると拡大できます</small>
          <figure class="hover-img">
            <%= link_to @carry_content.image, "data-lightbox": @carry_content.image do %>
              <%= image_tag @carry_content.image ,class:"img" %>
            <% end %>
            <figcaption>
              <p>画像をクリックして拡大</p>
            </figcaption>
          </figure>
          <% end %>
  </table>
</div>
<%= link_to "注文手続きへ", new_text_path, class: "btn btn-primary mt-3" %>
<%= link_to "買い物を続ける", new_picture_path, class: "btn btn-primary mt-5" %>

app/views/contents/new.html.erb
<h1>Contents#new</h1>
<p>Find me in app/views/contents/new.html.erb</p>

app/views/contents/update.html.erb
<h1>Contents#update</h1>
<p>Find me in app/views/contents/update.html.erb</p>

app/views/pictures/create.html.erb
<h1>注文情報入力</h1>

 <div class="field">
    <%= form_with model: @orders,url: public_orders_confirm_path, method: :post do |f| %>
   <h2> <%= f.label :支払方法 %></h2>
    <%= f.radio_button :payment_method, 0 %>
    <%= f.label :クレジットカード %> 
<br> <%= f.radio_button :payment_method, 1 %>
<%= f.label :銀行振込 %>
   

   <h2> お届け先</h2>
  <%= f.radio_button :address_option ,0 %>
    <%= f.label :ご自身の住所 %>
    <%= current_customer.postal_code %>
    <%= current_customer.address %>
    <%= current_customer.last_name %>
    <%= current_customer.first_name %><br>
    
    <%= f.radio_button :address_option ,1 %>
    <%= f.label :登録済住所から選択 %>
    <%= f.collection_select :address, Customer.all, :id, :address, { prompt: '選択してください' }, class: 'form-control' %><br>
    
  <%= f.radio_button :address_option ,2 %>
    <%= f.label :新しいお届け先 %><br>

    <%= f.label :郵便番号 %>
    <%= f.text_field :postal_code %><br>

    <%= f.label :住所 %>
    <%= f.text_field :address %><br>
    
        <%= f.label :宛名 %>
    <%= f.text_field :name %>   
        <%= f.submit "購入確認へ", class:"btn btn-primary btn-block btn-base-1 mt-20" %>
<% end %>
  </div>

app/views/pictures/index.html.erb
<td>
   <% if @item.image.attached? %>
    <%= image_tag @item.image, size: "300x200" %>
  <% else %>
    <%= image_tag 'no_image', size: "200x200" %>
  <% end %>
</td>
<td>
<h2><%= @item.name %></h2><br>
<h3><%= @item.introduction %><h3><br>
￥<%= @item.price %>(税込)<br>
  <%= form_with model: @cart_item , url: public_cart_items_path do |f| %>
  <%= f.hidden_field :item_id, :value => @item.id %>
  <%= f.select :amount, *[1..10] %>
    <%= f.submit 'カートに入れる' %>
<% end %>

</td>
<!-- form_with部分 -->

app/views/pictures/new.html.erb
<h1>2ページ目。写真投稿</h1>
<div class="alret">
  <%= flash[:alret] %>
</div>
<div class="col-md-8 offset-md-1">
<table class="table">
<tbody>
<tr>
<td>
  <%= form_with model: @carry_content, url: carry_contents_path do |f| %>
  <%= f.file_field :image, accept: "image/*" %>
      <%= f.submit '分析しよー', class: 'ui button' %>
<% end %>
</td>
</tr>
</tbody>
</table>
</div>

app/views/points/create.html.erb
<h1>Points#create</h1>
<p>Find me in app/views/points/create.html.erb</p>

app/views/points/index.html.erb
        <div class="start">
            <h6>Are you ready?</h6>
            <%= link_to "診断を始める", new_point_path, class: "link" %>
        </div>

app/views/points/new.html.erb
<%= form_for(@point, class: 'form-horizontal', role: 'form') do |f| %>
    <div class="container-sindan">
        <div class="row">
            <div class="col-12">
                <p>Question1. どちらかと言うと…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>じっくり考える方だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>考えるより行動する方だ</p>
            </div>

            <div class="col-12">
                <p>Question2. 自分の価値観として近い方は…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>周りの人と違う存在でありたい</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>周りと同じでいたい</p>
            </div>

            <div class="col-12">
                <p>Question3. 人と接するときは…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>相手の話をよく聞く方だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>自分の話をよくする方だ</p>
            </div>

            <div class="col-12">
                <p>Question4. 大切にしたいのは…</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "1", nil %>論理性だ</p>
            </div>
            <div class="col-6">
                <p><%= f.check_box :question, {multiple: true}, "2", nil %>情緒だ</p>
            </div>
        </div>
    </div>
    <div class="sindanbotan">
        <%= f.submit "post" %>
    </div>
<% end %>

app/views/points/show.html.erb
<div class="intoro">
  <h5>診断結果</h5>
  <p>あなたにおすすめの香りは…</p>
</div>

<div class="tweet-container">
  <div class="tweet">
    <% if @point.question == "1111" %>
    <h6>レモン</h6>
    <p>柑橘系の代表的な原料</p>
    <p>清涼感があり、爽やかな印象</p>
    
    <% elsif @point.question == "1112" %>
    <h6>シトラス</h6>
    <p>オレンジに似た柑橘系の果物</p>
    <p>リラックス効果がある</p>
    
    <% elsif @point.question == "1121" %>
    <h6>ローズ</h6>
    <p>華やかで上品な香り</p>
    <p>ストレスを緩和してくれる効果がある</p>
    
    <% elsif @point.question == "1122" %>
    <h6>ラベンダー</h6>
    <p>優しく女性らしい香り</p>
    <p>気持ちを落ち着かせてくれる</p>
    
    <% elsif @point.question == "1211" %>
    <h6>ジャスミン</h6>
    <p>爽やかなのに官能的な香り</p>
    <p>幸福感を得やすい</p>
    
    <% elsif @point.question == "1212" %>
    <h6>ピーチ</h6>
    <p>フレッシュで優しい香り</p>
    <p>アンチエイジングにも最適</p>
    
    <% elsif @point.question == "1221" %>
    <h6>アップル</h6>
    <p>特徴的で甘い香り</p>
    <p>万人受けしやすい</p>
    
    <% elsif @point.question == "1222" %>
    <h6>ユーカリ</h6>
    <p>しっかりとした優しい香り</p>
    <p>浄化作用があり。気持ちを落ち着かせてくれる</p>
    
    <% elsif @point.question == "2111" %>
    <h6>ローズマリー</h6>
    <p>きりりとした強めの香りが特徴的</p>
    <p>美容効果が高い</p>
    
    <% elsif @point.question == "2112" %>
    <h6>ベルガモット</h6>
    <p>柑橘系の果実</p>
    <p>甘くてフレッシュな、万能な香料</p>
    
    <% elsif @point.question == "2121" %>
    <h6>ムスク</h6>
    <p>雄のジャコウジカの腹部にある香嚢から抽出した香料</p>
    <p>官能的で重い香り</p>
    
    <% elsif @point.question == "2122" %>
    <h6>アンバー</h6>
    <p>マッコウクジラの結石から抽出した香料</p>
    <p>魅惑的で色気のある香り</p>
    
    <% elsif @point.question == "2211" %>
    <h6>シナモン</h6>
    <p>甘いスパイスの香り</p>
    <p>香水のアクセントとしてよく使われる</p>
    
    <% elsif @point.question == "2212" %>
    <h6>バニラ</h6>
    <p>甘くて官能的な香り</p>
    <p>上品で年齢を問わず人気が高い</p>
    
    <% elsif @point.question == "2221" %>
    <h6>イランイラン</h6>
    <p>色気のある濃厚で甘い香り</p>
    <p>恋愛に効果があり</p>
    
    <% elsif @point.question == "2222" %>
    <h6>サンダルウッド</h6>
    <p>お香としてよく使われる白檀の香り</p>
    <p>集中力を高める効果もあり</p>
    
    <% end %>
    
  </div>
</div>
<button class="ui button"><%= link_to "ふかぼりへ進む", new_content_path, class: "nav-link bi bi-chat-left-dots-fill" %></button>

app/views/texts/create.html.erb
<h1>Texts#create</h1>
<p>Find me in app/views/texts/create.html.erb</p>

app/views/texts/destroy.html.erb
<h1>Texts#destroy</h1>
<p>Find me in app/views/texts/destroy.html.erb</p>

app/views/texts/edit.html.erb
<h1>Texts#edit</h1>
<p>Find me in app/views/texts/edit.html.erb</p>

app/views/texts/new.html.erb
<h1>3ページ目。ラスト。テキスト投稿</h1>
<div class="alret">
  <%= flash[:alret] %>
</div>

 <% @carry_content.each do |carry_content| %>
    <%= image_tag carry_content.picture.image, size: "100x100" %>
 <% end %>
 


<%= form_with model: @carry_content, url: new_text_path do |f| %>
<%= f.text_area :text, placeholder: "Gペン" %>
<%= f.hidden_field :text_id, :value => @text.id %>
<%= f.submit '分析しよー', class: 'ui button' %>

 <% end %>

</div>

app/views/texts/show.html.erb
<div class="col-md-8 offset-md-1">
<h1>注文情報確認</h1>
<table>
    <tr>
     <th></th>
      <th>商品名</th>
      <th>単価（税込）</th>
      <th>数量</th>
      <th>小計</th>
      <th></th>
    </tr>
     <% @cart_item.each do |cart_item| %>
     <tr>
      <td>  <% if cart_item.item.image.attached? %>
    <%= image_tag cart_item.item.image, size: "100x100" %>
    <% else %>
      <%= image_tag 'no_image', size: "2x2" %>
    <% end %></td>
      <td><%= cart_item.item.name %></td>
      <td>￥<%= cart_item.item.price %></td>
      <td> <%= cart_item.amount %> </td>
      <td><%= cart_item.item.price*cart_item.amount %> </td>
<% @total=@total+cart_item.item.price*cart_item.amount %>
 <% end %>
    </td>
  </table>
<table style="margin-top: 50px;">
    <tr>
      <th>送料</th>
      <td><%= @postage %></td>
 </tr>
    <tr>
      <th>商品合計</th>
      <td><%= @total %></td>
 </tr>
    <tr>
      <th>請求金額</th>
      <td><%= @postage + @total %></td>
 </tr>
  </table>
  <h2>支払方法</h2>
  <p> <%= @payment_method %></p>
  <h2>お届け先</h2>
      <p>〒<%= @order.postal_code %><%= @order.address %><%= @order.name %>
</div>


  <%= form_with model: @order , url: public_orders_complete_path do |f| %>
  <%= f.hidden_field :postal_code, :value => @order.postal_code %>
   <%= f.hidden_field :address, :value => @order.address %>
   <%= f.hidden_field :name, :value => @order.name %>
   <%= f.hidden_field :customer_id, :value => current_customer.id %>
   <%= f.hidden_field :shipping_cost, :value => @postage %>
    <%= f.hidden_field :total_payment, :value => @total %>
   <%= f.hidden_field :payment_method, :value => @payment_method %>
    <%= f.submit '購入確定' %>
<% end %>

app/views/texts/update.html.erb
<h1>Texts#update</h1>
<p>Find me in app/views/texts/update.html.erb</p>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>